//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naselja
    {
        public int NaseljeId { get; set; }
        public string Naselje { get; set; }
        public string PBroj { get; set; }
        public string Država { get; set; }
    }
}
